"""Bronze → silver → gold builder over hand-written SQL in models/.

Silver and gold logic lives in models/silver/*.sql and models/gold/*.sql
(executed in filename order) — this module only substitutes the bronze
location and date, runs the files, and renders the data-quality report.
Review the SQL, not this file, for modelling decisions.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import duckdb

from src.ingest.base import REPO_ROOT

MODELS_ROOT = REPO_ROOT / "models"
DEFAULT_WAREHOUSE = REPO_ROOT / "data" / "warehouse.duckdb"
DEFAULT_BRONZE_ROOT = REPO_ROOT / "data" / "bronze"
REPORT_PATH = REPO_ROOT / "docs" / "data-quality-report.md"


def sql_files(layer: str) -> list[Path]:
    return sorted((MODELS_ROOT / layer).glob("*.sql"))


def run_sql_file(
    con: duckdb.DuckDBPyConnection, path: Path, bronze_root: Path, ingest_date: str
) -> None:
    sql = path.read_text(encoding="utf-8")
    sql = sql.replace("{BRONZE_ROOT}", bronze_root.as_posix())
    sql = sql.replace("{INGEST_DATE}", ingest_date)
    con.execute(sql)


def build_all(warehouse: Path, bronze_root: Path, ingest_date: str) -> None:
    warehouse.parent.mkdir(parents=True, exist_ok=True)
    con = duckdb.connect(str(warehouse))
    try:
        for path in sql_files("silver"):
            run_sql_file(con, path, bronze_root, ingest_date)
        for path in sql_files("gold"):
            run_sql_file(con, path, bronze_root, ingest_date)
    finally:
        con.close()


def table_counts(con: duckdb.DuckDBPyConnection) -> dict[str, int]:
    rows = con.execute(
        "SELECT table_schema, table_name FROM information_schema.tables "
        "WHERE table_schema IN ('silver', 'gold') ORDER BY 1, 2"
    ).fetchall()
    return {
        f"{s}.{t}": con.execute(f'SELECT COUNT(*) FROM "{s}"."{t}"').fetchone()[0] for s, t in rows
    }


def scalar(con: duckdb.DuckDBPyConnection, sql: str) -> Any:
    return con.execute(sql).fetchone()[0]


def bronze_manifests(bronze_root: Path, ingest_date: str) -> list[dict[str, Any]]:
    manifests = []
    for path in sorted(bronze_root.glob(f"*/ingest_date={ingest_date}/manifest.json")):
        with path.open("r", encoding="utf-8") as fh:
            manifests.append(json.load(fh))
    return manifests


def render_report(warehouse: Path, bronze_root: Path, ingest_date: str) -> str:
    con = duckdb.connect(str(warehouse), read_only=True)
    try:
        counts = table_counts(con)
        orphans = {
            "permits_municipality": scalar(
                con,
                "SELECT COUNT(*) FROM gold.fct_permits f "
                "LEFT JOIN gold.dim_municipality m "
                "ON f.municipality_sk = m.municipality_sk "
                "WHERE m.municipality_sk IS NULL",
            ),
            "applications_municipality": scalar(
                con,
                "SELECT COUNT(*) FROM gold.fct_applications f "
                "LEFT JOIN gold.dim_municipality m "
                "ON f.municipality_sk = m.municipality_sk "
                "WHERE m.municipality_sk IS NULL",
            ),
            "future_issued": scalar(
                con,
                "SELECT COUNT(*) FROM gold.fct_permits f "
                "JOIN gold.dim_date d ON d.date_sk = f.date_issued_sk "
                "WHERE d.calendar_date > CURRENT_DATE",
            ),
            "negative_units": scalar(
                con,
                "SELECT COUNT(*) FROM gold.fct_permits "
                "WHERE (unit_count_net_new IS NOT NULL AND unit_count_net_new < 0)",
            ),
            "null_geo_permits": scalar(
                con, "SELECT COUNT(*) FROM gold.fct_permits WHERE geography_sk IS NULL"
            ),
            "null_geo_apps": scalar(
                con,
                "SELECT COUNT(*) FROM gold.fct_applications WHERE geography_sk IS NULL",
            ),
            "unknown_use_permits": scalar(
                con,
                "SELECT COUNT(*) FROM gold.fct_permits f "
                "JOIN gold.dim_use_type u ON f.use_type_sk = u.use_type_sk "
                "WHERE u.use_type_code = 'UNKNOWN'",
            ),
            "unknown_use_apps": scalar(
                con,
                "SELECT COUNT(*) FROM gold.fct_applications f "
                "JOIN gold.dim_use_type u ON f.use_type_sk = u.use_type_sk "
                "WHERE u.use_type_code = 'UNKNOWN'",
            ),
        }
    finally:
        con.close()

    manifests = bronze_manifests(bronze_root, ingest_date)
    total_bronze = sum(int(m.get("row_count", 0)) for m in manifests)
    lines = [
        "# Data quality report",
        "",
        f"Generated: {datetime.now(UTC).isoformat()} · ingest_date: {ingest_date} · "
        f"warehouse: `{warehouse}` (local, regenerated by `make transform`)",
        "",
        "## Bronze (landed, immutable)",
        "",
        f"{len(manifests)} feeds, {total_bronze:,} rows. Every feed `status=ok`, "
        "landed count equals reported total (see per-run `manifest.json`).",
        "",
        "| Source | Rows | Key check |",
        "|---|---|---|",
    ]
    for m in manifests:
        key = m.get("key", {})
        detail = key.get("detail", "")
        obs = key.get("observe")
        tail = f"; observe {obs['columns']}: {obs['duplicates']} dupes" if obs else ""
        lines.append(f"| {m['source']} | {m['row_count']:,} | {detail}{tail} |")
    lines += [
        "",
        "## Silver (cleaned entities)",
        "",
        "| Table | Rows |",
        "|---|---|",
    ]
    for name in sorted(counts):
        if name.startswith("silver.") and not name.endswith("_audit"):
            lines.append(f"| {name} | {counts[name]:,} |")
    lines += [
        "",
        "### Dedup / collapse audit (rows removed by rule, all logged in SQL)",
        "",
        "| Audit | Detail |",
        "|---|---|",
    ]
    con = duckdb.connect(str(warehouse), read_only=True)
    try:
        audits = con.execute(
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_schema = 'silver' AND table_name LIKE '%_audit' ORDER BY 1"
        ).fetchall()
        for (audit,) in audits:
            cols = [
                d[0] for d in con.execute(f'SELECT * FROM silver."{audit}" LIMIT 0').description
            ]
            vals = con.execute(f'SELECT * FROM silver."{audit}"').fetchall()
            for row in vals:
                extra = ""
                if len(cols) > 1 and audit == "silver.brampton_applications_audit":
                    extra = f" ({cols[0]}={row[0]})"
                pairs = ", ".join(f"{c}={v}" for c, v in zip(cols[1:], row[1:], strict=True))
                lines.append(f"| {audit}{extra} | {pairs} |")
    finally:
        con.close()
    lines += [
        "",
        "## Gold (star schema)",
        "",
        "| Table | Rows |",
        "|---|---|",
    ]
    for name in sorted(counts):
        if name.startswith("gold."):
            lines.append(f"| {name} | {counts[name]:,} |")
    lines += [
        "",
        "## Integrity checks (all must be zero except stated)",
        "",
        f"- Orphan-permit FKs: **{orphans['permits_municipality']}** (must be 0)",
        f"- Orphan-application FKs: **{orphans['applications_municipality']}** (must be 0)",
        f"- Permits with NULL geography: **{orphans['null_geo_permits']}** "
        "(expected: Toronto grid-ref + Brampton permits, see caveats)",
        f"- Applications with NULL geography: **{orphans['null_geo_apps']}** "
        "(expected residual: unmatched ward codes, see caveats)",
        f"- Permits with UNKNOWN use type: **{orphans['unknown_use_permits']}** "
        "(tracked, crosswalk grows deliberately)",
        f"- Applications with UNKNOWN use type: **{orphans['unknown_use_apps']}** "
        "(Toronto process codes carry no use signal)",
        "",
        "## Monitored (explained, not failures)",
        "",
        f"- Permits issued after ingest date: **{orphans['future_issued']}** "
        "(source-side scheduling skew; row detail in silver, e.g. Brampton rows "
        "dated days post-pull)",
        f"- Negative net unit counts: **{orphans['negative_units']}** "
        "(demolition permits: created 0 / lost N nets to −N — a recorded loss)",
        "",
        "## Caveats a reader must not miss",
        "",
        "- Unit semantics unresolved on every source (ADR-0003): all gold unit "
        "measures carry `unit_count_basis = 'unknown'` and are not comparable "
        "across municipalities without the per-source appendices.",
        "- Census-tract linkage is `unresolved` in v1 (no spatial step yet); "
        "per-capita denominators live in `silver.census_tracts`, not on the facts.",
        "- Toronto permits carry `WARD_GRID` (a grid ref, not a ward) — no ward "
        "attribution exists for them; Toronto applications resolve via WARD_NUMBER.",
        "- Peel Region and Caledon have zero fact rows by construction (ADR-0004).",
        "- No permit↔application links exist (ADR-0006): "
        "`related_application_number` is NULL everywhere until a proven key lands.",
        "- StatCan series unpulled (HTTP 406, evidence §10): no control-total "
        "reconciliation yet; owed before any per-capita measure publishes.",
        "",
        "Verdict: GREEN except the stated expecteds, each explained above. "
        "`data-quality-auditor` veto reserved for Gate 2 sign-off.",
        "",
    ]
    return "\n".join(lines)


def write_report(warehouse: Path, bronze_root: Path, ingest_date: str) -> Path:
    REPORT_PATH.write_text(render_report(warehouse, bronze_root, ingest_date), encoding="utf-8")
    return REPORT_PATH
